using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace APICore_SoanDeThi.Migrations
{
    public partial class UpdateDB : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Question",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Title = table.Column<string>(type: "text", nullable: true),
                    OptionA = table.Column<string>(type: "text", nullable: true),
                    OptionB = table.Column<string>(type: "text", nullable: true),
                    OptionC = table.Column<string>(type: "text", nullable: true),
                    OptionD = table.Column<string>(type: "text", nullable: true),
                    CorrectOption = table.Column<byte>(type: "smallint", nullable: false),
                    Class = table.Column<byte>(type: "smallint", nullable: false),
                    Level = table.Column<byte>(type: "smallint", nullable: false),
                    CreateDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    CreateBy = table.Column<long>(type: "bigint", nullable: false),
                    ModifyDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    ModifyBy = table.Column<long>(type: "bigint", nullable: false),
                    IsDisabled = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Question", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "ViewNhanVien",
                columns: table => new
                {
                    IdNv = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Manv = table.Column<string>(type: "text", nullable: true),
                    Holot = table.Column<string>(type: "text", nullable: true),
                    Ten = table.Column<string>(type: "text", nullable: true),
                    Phai = table.Column<string>(type: "text", nullable: true),
                    Ngaysinh = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    ThuongtruDiachi = table.Column<string>(type: "text", nullable: true),
                    ThuongtruTinh = table.Column<long>(type: "bigint", nullable: true),
                    ThuongtruHuyen = table.Column<long>(type: "bigint", nullable: true),
                    ThuongtruPhone = table.Column<string>(type: "text", nullable: true),
                    TamtruDiachi = table.Column<string>(type: "text", nullable: true),
                    TamtruTinh = table.Column<long>(type: "bigint", nullable: true),
                    TamtruHuyen = table.Column<long>(type: "bigint", nullable: true),
                    TamtruPhone = table.Column<string>(type: "text", nullable: true),
                    Mobile = table.Column<string>(type: "text", nullable: true),
                    Email = table.Column<string>(type: "text", nullable: true),
                    Tinh = table.Column<long>(type: "bigint", nullable: true),
                    Dantoc = table.Column<long>(type: "bigint", nullable: true),
                    Tongiao = table.Column<long>(type: "bigint", nullable: true),
                    Cmnd = table.Column<string>(type: "text", nullable: true),
                    Ngaycap = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Noicap = table.Column<string>(type: "text", nullable: true),
                    Passport = table.Column<string>(type: "text", nullable: true),
                    Ngaycappassport = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Noicappassport = table.Column<string>(type: "text", nullable: true),
                    IdChucdanh = table.Column<long>(type: "bigint", nullable: true),
                    Chucvu = table.Column<long>(type: "bigint", nullable: true),
                    Tinhtranghn = table.Column<long>(type: "bigint", nullable: true),
                    Ngayvaodoan = table.Column<string>(type: "text", nullable: true),
                    Ngayvaodang = table.Column<string>(type: "text", nullable: true),
                    Quanhegiadinh = table.Column<string>(type: "text", nullable: true),
                    Quatrinhhoctap = table.Column<string>(type: "text", nullable: true),
                    Kynangngonngu = table.Column<string>(type: "text", nullable: true),
                    Quatrinhcongtac = table.Column<string>(type: "text", nullable: true),
                    Masothue = table.Column<string>(type: "text", nullable: true),
                    Mataikhoan = table.Column<string>(type: "text", nullable: true),
                    Sotaikhoan = table.Column<string>(type: "text", nullable: true),
                    IdNganhang = table.Column<long>(type: "bigint", nullable: true),
                    Bangcap = table.Column<long>(type: "bigint", nullable: true),
                    Trinhdo = table.Column<string>(type: "text", nullable: true),
                    Chuyenmon = table.Column<string>(type: "text", nullable: true),
                    Bangcapkhac = table.Column<string>(type: "text", nullable: true),
                    Dongbhxh = table.Column<short>(type: "smallint", nullable: true),
                    Sosobhxh = table.Column<string>(type: "text", nullable: true),
                    Ngaycapsobhxh = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Dongbhyt = table.Column<short>(type: "smallint", nullable: true),
                    Sothebhyt = table.Column<string>(type: "text", nullable: true),
                    Ngaycapthebhyt = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Ngayhethanbhxh = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Ngayhethanbhyt = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Thangthamgiabh = table.Column<int>(type: "integer", nullable: true),
                    Namthamgiabh = table.Column<int>(type: "integer", nullable: true),
                    Noidangkykcb = table.Column<long>(type: "bigint", nullable: true),
                    Filecv = table.Column<string>(type: "text", nullable: true),
                    Disable = table.Column<short>(type: "smallint", nullable: true),
                    Ngayvaocty = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Ngayvaobienche = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Loainhanvien = table.Column<long>(type: "bigint", nullable: true),
                    Sogiolamviec = table.Column<double>(type: "double precision", nullable: true),
                    Thoiviec = table.Column<short>(type: "smallint", nullable: true),
                    Soqdthoiviec = table.Column<string>(type: "text", nullable: true),
                    Loaithoiviec = table.Column<int>(type: "integer", nullable: true),
                    Ngaythoiviec = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Ngaykythoiviec = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Nguoikythoiviec = table.Column<string>(type: "text", nullable: true),
                    Hinhthucthoiviec = table.Column<int>(type: "integer", nullable: true),
                    Lydothoiviec = table.Column<string>(type: "text", nullable: true),
                    Trocapthoiviec = table.Column<string>(type: "text", nullable: true),
                    Boithuongthoiviec = table.Column<string>(type: "text", nullable: true),
                    Trathe = table.Column<short>(type: "smallint", nullable: true),
                    Ngaytrathe = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Tamnghi = table.Column<short>(type: "smallint", nullable: true),
                    Luongcb = table.Column<string>(type: "text", nullable: true),
                    Luongkd = table.Column<string>(type: "text", nullable: true),
                    IdTo = table.Column<long>(type: "bigint", nullable: true),
                    IdBp = table.Column<long>(type: "bigint", nullable: true),
                    IdDv = table.Column<long>(type: "bigint", nullable: true),
                    IdCa = table.Column<string>(type: "text", nullable: true),
                    Songayphep = table.Column<int>(type: "integer", nullable: true),
                    IdQuanly = table.Column<long>(type: "bigint", nullable: true),
                    IdCvquanly = table.Column<long>(type: "bigint", nullable: true),
                    Code = table.Column<string>(type: "text", nullable: true),
                    ExtraId = table.Column<string>(type: "text", nullable: true),
                    Sosolaodong = table.Column<string>(type: "text", nullable: true),
                    Ngaycapsolaodong = table.Column<string>(type: "text", nullable: true),
                    Thanhtoanquanh = table.Column<short>(type: "smallint", nullable: true),
                    Ghichu = table.Column<string>(type: "text", nullable: true),
                    Hocham = table.Column<string>(type: "text", nullable: true),
                    Quoctich = table.Column<string>(type: "text", nullable: true),
                    Loaihopdong = table.Column<int>(type: "integer", nullable: true),
                    Chucdanh = table.Column<int>(type: "integer", nullable: true),
                    Bhtn = table.Column<short>(type: "smallint", nullable: true),
                    Cd = table.Column<short>(type: "smallint", nullable: true),
                    Tenchucvu = table.Column<string>(type: "text", nullable: true),
                    Tenchucdanh = table.Column<string>(type: "text", nullable: true),
                    Namsinh = table.Column<string>(type: "text", nullable: true),
                    Datecreated = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Lastmodified = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Createduser = table.Column<long>(type: "bigint", nullable: true),
                    Lastmodifieduser = table.Column<long>(type: "bigint", nullable: true),
                    Kiemnhiem = table.Column<long>(type: "bigint", nullable: true),
                    Bcbhxht = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Kinhnghiemlvnh = table.Column<double>(type: "double precision", nullable: true),
                    Songuoiphuthuoc = table.Column<int>(type: "integer", nullable: true),
                    Alloweditchucdanh = table.Column<short>(type: "smallint", nullable: true),
                    Lastupdate = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Lanbaotangbhxh = table.Column<int>(type: "integer", nullable: true),
                    Lanbaogiambhxh = table.Column<int>(type: "integer", nullable: true),
                    IdHs = table.Column<long>(type: "bigint", nullable: true),
                    Ngaythamgiabhxh = table.Column<string>(type: "text", nullable: true),
                    IdCvtd = table.Column<long>(type: "bigint", nullable: true),
                    Macd = table.Column<string>(type: "text", nullable: true),
                    IdChucdanhluanchuyen = table.Column<long>(type: "bigint", nullable: true),
                    IdHd = table.Column<long>(type: "bigint", nullable: true),
                    Sothe = table.Column<string>(type: "text", nullable: true),
                    IdChedonghi = table.Column<long>(type: "bigint", nullable: true),
                    Luongvtcv = table.Column<string>(type: "text", nullable: true),
                    Alloweditsalary = table.Column<short>(type: "smallint", nullable: true),
                    Ngayhethanthuviec = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Sotaikhoan1 = table.Column<string>(type: "text", nullable: true),
                    Tinhluongrieng = table.Column<short>(type: "smallint", nullable: true),
                    Cachtinhthuetncn = table.Column<int>(type: "integer", nullable: true),
                    Trinhdovitinh = table.Column<long>(type: "bigint", nullable: true),
                    Trinhdoquanlynhanuoc = table.Column<long>(type: "bigint", nullable: true),
                    Trinhdochinhtri = table.Column<long>(type: "bigint", nullable: true),
                    Ngayvaodangchinthuc = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Tinhtrangsuckhoe = table.Column<string>(type: "text", nullable: true),
                    Chieucao = table.Column<int>(type: "integer", nullable: true),
                    Cannang = table.Column<double>(type: "double precision", nullable: true),
                    Ngaynhapngu = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Ngayxuatngu = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Quanham = table.Column<long>(type: "bigint", nullable: true),
                    Nhommau = table.Column<int>(type: "integer", nullable: true),
                    Giadinhchinhsach = table.Column<long>(type: "bigint", nullable: true),
                    Ghichuquansu = table.Column<string>(type: "text", nullable: true),
                    Hangthuongbinh = table.Column<int>(type: "integer", nullable: true),
                    Luongthuviec = table.Column<string>(type: "text", nullable: true),
                    Sogplx = table.Column<string>(type: "text", nullable: true),
                    Ngaycapgplx = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Noicapgplx = table.Column<long>(type: "bigint", nullable: true),
                    Ngayhethangplx = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Diadiemlamviec = table.Column<long>(type: "bigint", nullable: true),
                    Nickname = table.Column<string>(type: "text", nullable: true),
                    Chucvutrongdoan = table.Column<string>(type: "text", nullable: true),
                    Noivaodang = table.Column<string>(type: "text", nullable: true),
                    Nguoigioithieu1 = table.Column<string>(type: "text", nullable: true),
                    Congviecnoio1 = table.Column<string>(type: "text", nullable: true),
                    Nguoigioithieu2 = table.Column<string>(type: "text", nullable: true),
                    Congviecnoio2 = table.Column<string>(type: "text", nullable: true),
                    Noivaodangchinhthuc = table.Column<string>(type: "text", nullable: true),
                    Sothedang = table.Column<string>(type: "text", nullable: true),
                    Ngaycapthedang = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Noicapthedang = table.Column<string>(type: "text", nullable: true),
                    Chucvutrongdang = table.Column<string>(type: "text", nullable: true),
                    Hangbenhbinh = table.Column<int>(type: "integer", nullable: true),
                    Hoancanhnhao = table.Column<string>(type: "text", nullable: true),
                    Ngaythamgiacongdoan = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Chucvucongdoan = table.Column<string>(type: "text", nullable: true),
                    Tennguyenquan = table.Column<string>(type: "text", nullable: true),
                    Ngaybatdaudongbhxh = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Ngaybatdaudongbhtn = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Ngaytrasobhxh = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Datrasobhxh = table.Column<short>(type: "smallint", nullable: true),
                    Diemmanh = table.Column<string>(type: "text", nullable: true),
                    Diemyeu = table.Column<string>(type: "text", nullable: true),
                    Ghichuthoiviec = table.Column<string>(type: "text", nullable: true),
                    Status = table.Column<int>(type: "integer", nullable: true),
                    Toadodiachitamtru = table.Column<string>(type: "text", nullable: true),
                    Toadodiachithuongtru = table.Column<string>(type: "text", nullable: true),
                    Filethoiviec = table.Column<string>(type: "text", nullable: true),
                    Tentruongtotnghiep = table.Column<string>(type: "text", nullable: true),
                    Loaigiangvien = table.Column<long>(type: "bigint", nullable: true),
                    IdKhoa = table.Column<long>(type: "bigint", nullable: true),
                    Mongiangday = table.Column<string>(type: "text", nullable: true),
                    Chuyennganh = table.Column<string>(type: "text", nullable: true),
                    Tinhtrang = table.Column<long>(type: "bigint", nullable: true),
                    Totnghiepnganh = table.Column<string>(type: "text", nullable: true),
                    Noinamtotnghiep = table.Column<string>(type: "text", nullable: true),
                    Hesogv = table.Column<double>(type: "double precision", nullable: true),
                    IdChucdanhGv = table.Column<long>(type: "bigint", nullable: true),
                    Cachtinhluong = table.Column<int>(type: "integer", nullable: true),
                    Noisinh = table.Column<string>(type: "text", nullable: true),
                    Calamviec = table.Column<long>(type: "bigint", nullable: true),
                    Tinhtranghonnhan = table.Column<string>(type: "text", nullable: true),
                    Batdautungay = table.Column<int>(type: "integer", nullable: true),
                    Ngayvaongachvienchuc = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Hangchucdanh = table.Column<long>(type: "bigint", nullable: true),
                    Cachchamcong = table.Column<int>(type: "integer", nullable: true),
                    IdChedolamviec = table.Column<long>(type: "bigint", nullable: true),
                    Truongtotnghiep = table.Column<long>(type: "bigint", nullable: true),
                    Luongchenhlech = table.Column<string>(type: "text", nullable: true),
                    IsdongpcdDn = table.Column<short>(type: "smallint", nullable: true),
                    Emailcanhan = table.Column<string>(type: "text", nullable: true),
                    Ngayketthucdaotao = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Ngaybatdauthuviec = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Chutaikhoan = table.Column<string>(type: "text", nullable: true),
                    IdNganhhoc = table.Column<long>(type: "bigint", nullable: true),
                    Namtotnghiep = table.Column<int>(type: "integer", nullable: true),
                    IdBangtotnghiep = table.Column<long>(type: "bigint", nullable: true),
                    Ngayhethanpassport = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Projectid = table.Column<long>(type: "bigint", nullable: true),
                    Sosobhyt = table.Column<string>(type: "text", nullable: true),
                    Ghichubhxh = table.Column<string>(type: "text", nullable: true),
                    IdNvcu = table.Column<long>(type: "bigint", nullable: true),
                    Nguoilienhe = table.Column<string>(type: "text", nullable: true),
                    QuanheNguoilienhe = table.Column<string>(type: "text", nullable: true),
                    SodienthoaiNguoilienhe = table.Column<string>(type: "text", nullable: true),
                    Chinhanhnganhang = table.Column<string>(type: "text", nullable: true),
                    Hinhthucluong = table.Column<int>(type: "integer", nullable: true),
                    DiachiNguoilienhe = table.Column<string>(type: "text", nullable: true),
                    Isforeigner = table.Column<short>(type: "smallint", nullable: true),
                    Iskycamketthue = table.Column<short>(type: "smallint", nullable: true),
                    Languoikhuyettat = table.Column<short>(type: "smallint", nullable: true),
                    Noidungcancu = table.Column<string>(type: "text", nullable: true),
                    Noidungnoinhan = table.Column<string>(type: "text", nullable: true),
                    Songayphepconlai = table.Column<decimal>(type: "numeric", nullable: true),
                    Truvaoluongthang = table.Column<string>(type: "text", nullable: true),
                    Ghichutrudongphuc = table.Column<string>(type: "text", nullable: true),
                    Iscutrutren180ngay = table.Column<short>(type: "smallint", nullable: true),
                    Enrollnumber = table.Column<int>(type: "integer", nullable: true),
                    Staffgroupid = table.Column<int>(type: "integer", nullable: true),
                    Luongcoban = table.Column<string>(type: "text", nullable: true),
                    Trocapkhac = table.Column<string>(type: "text", nullable: true),
                    Tongthunhap = table.Column<string>(type: "text", nullable: true),
                    Danhanviec = table.Column<short>(type: "smallint", nullable: true),
                    Ngaynhanviecdukien = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Dathongbao = table.Column<int>(type: "integer", nullable: true),
                    Ngaybatdautinhthamnien = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Iskhongkhautruttncn = table.Column<short>(type: "smallint", nullable: true),
                    Tenbv = table.Column<string>(type: "text", nullable: true),
                    Ngaycapbhyt = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Mabenhvien = table.Column<string>(type: "text", nullable: true),
                    Isluonggross = table.Column<int>(type: "integer", nullable: true),
                    NanocoIsphobiennoiquy = table.Column<short>(type: "smallint", nullable: true),
                    Nguontuyendungid = table.Column<long>(type: "bigint", nullable: true),
                    Congtrocapvaoluongthang = table.Column<string>(type: "text", nullable: true),
                    NanocoCackhoanbosungkhac = table.Column<string>(type: "text", nullable: true),
                    ThuongtruXa = table.Column<long>(type: "bigint", nullable: true),
                    Sosohokhau = table.Column<string>(type: "text", nullable: true),
                    Tenchuho = table.Column<string>(type: "text", nullable: true),
                    Quanhevoichuho = table.Column<string>(type: "text", nullable: true),
                    TamtruXa = table.Column<long>(type: "bigint", nullable: true),
                    Mauinid = table.Column<int>(type: "integer", nullable: true),
                    Ngaybatdaudaotao = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Isprint = table.Column<short>(type: "smallint", nullable: true),
                    ThoiviecNgayvietdon = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Ngaysinhchuho = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    NgaythamgiaOt = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Ischeck = table.Column<short>(type: "smallint", nullable: true),
                    ReNgaythamgiaOt = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    ThoiviecLydoEn = table.Column<string>(type: "text", nullable: true),
                    Namsinhchuho = table.Column<string>(type: "text", nullable: true),
                    ThoiviecNgaythoiviectheodon = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Ngaybaogiambhxh = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Ngaycapmst = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Cancuthoiviec = table.Column<string>(type: "text", nullable: true),
                    Defaultmoduleid = table.Column<string>(type: "text", nullable: true),
                    Cocauid = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ViewNhanVien", x => x.IdNv);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Question");

            migrationBuilder.DropTable(
                name: "ViewNhanVien");
        }
    }
}
