// <auto-generated />
using System;
using APICore_SoanDeThi.Models.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace APICore_SoanDeThi.Migrations
{
    [DbContext(typeof(SoanDeThi_DbContext))]
    [Migration("20210801071604_CreateDbMonHoc")]
    partial class CreateDbMonHoc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.BaiHoc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("IdChuong")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MaBaiHoc")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("NguoiSua")
                        .HasColumnType("bigint");

                    b.Property<long>("NguoiTao")
                        .HasColumnType("bigint");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("integer");

                    b.Property<string>("TenBaiHoc")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BaiHoc");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.BaiKiemTra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("IdGroup")
                        .HasColumnType("bigint");

                    b.Property<string>("MaDe")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BaiKiemTra");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.BaiKiemTra_ChiTiet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("IdBaiKiemTra")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCauHoi")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BaiKiemTra_ChiTiet");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.BaiKiemTra_Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CauDe")
                        .HasColumnType("integer");

                    b.Property<int>("CauKho")
                        .HasColumnType("integer");

                    b.Property<int>("CauTrungBinh")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<byte>("Lop")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("NguoiSua")
                        .HasColumnType("bigint");

                    b.Property<long>("NguoiTao")
                        .HasColumnType("bigint");

                    b.Property<int>("SoLuongDe")
                        .HasColumnType("integer");

                    b.Property<string>("TenBaiKiemTra")
                        .HasColumnType("text");

                    b.Property<short>("TrangThai")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("BaiKiemTra_Group");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.ChuongMonHoc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("IdMonHoc")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<byte>("Lop")
                        .HasColumnType("smallint");

                    b.Property<string>("MaChuong")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("NguoiSua")
                        .HasColumnType("bigint");

                    b.Property<long>("NguoiTao")
                        .HasColumnType("bigint");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("integer");

                    b.Property<string>("TenChuong")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChuongMonHoc");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.MonHoc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MaMonHoc")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("NguoiSua")
                        .HasColumnType("bigint");

                    b.Property<long>("NguoiTao")
                        .HasColumnType("bigint");

                    b.Property<string>("TenMonHoc")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.PqMainMenu", b =>
                {
                    b.Property<long>("IdMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AllowCode")
                        .HasColumnType("text");

                    b.Property<long?>("AllowPermit")
                        .HasColumnType("bigint");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<long?>("IdModule")
                        .HasColumnType("bigint");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<short?>("Position")
                        .HasColumnType("smallint");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("IdMain");

                    b.ToTable("PqMainMenu");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.PqModule", b =>
                {
                    b.Property<long>("IdModule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AllowCode")
                        .HasColumnType("text");

                    b.Property<long?>("AllowPermit")
                        .HasColumnType("bigint");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<short?>("Position")
                        .HasColumnType("smallint");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("IdModule");

                    b.ToTable("PqModule");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.PqSubMenu", b =>
                {
                    b.Property<long>("IdSubMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AllowCode")
                        .HasColumnType("text");

                    b.Property<long?>("AllowPermit")
                        .HasColumnType("bigint");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<long?>("IdMainMenu")
                        .HasColumnType("bigint");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("PageKey")
                        .HasColumnType("text");

                    b.Property<short?>("Position")
                        .HasColumnType("smallint");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("IdSubMenu");

                    b.ToTable("PqSubMenu");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte>("Class")
                        .HasColumnType("smallint");

                    b.Property<byte>("CorrectOption")
                        .HasColumnType("smallint");

                    b.Property<long>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<byte>("Level")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifyBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OptionA")
                        .HasColumnType("text");

                    b.Property<string>("OptionB")
                        .HasColumnType("text");

                    b.Property<string>("OptionC")
                        .HasColumnType("text");

                    b.Property<string>("OptionD")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.SysAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("NguoiTao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SysAttachment");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.SysAttachmentDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("AttachmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<bool>("IsDisable")
                        .HasColumnType("boolean");

                    b.Property<string>("LoaiFile")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("NguoiSua")
                        .HasColumnType("bigint");

                    b.Property<long>("NguoiTao")
                        .HasColumnType("bigint");

                    b.Property<string>("TenFile")
                        .HasColumnType("text");

                    b.Property<string>("TenFileGoc")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SysAttachmentDetail");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.ViewAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("Authentype")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Createddate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DPassword")
                        .HasColumnType("text");

                    b.Property<int?>("Defaultmodule")
                        .HasColumnType("integer");

                    b.Property<short?>("Disable")
                        .HasColumnType("smallint");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Expirevalidate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Exppassword")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Faillogin")
                        .HasColumnType("integer");

                    b.Property<long?>("IdNv")
                        .HasColumnType("bigint");

                    b.Property<short?>("Isadmin")
                        .HasColumnType("smallint");

                    b.Property<short?>("Iscreateldapaccount")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Lastlogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Lastpasschg")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Lastsend")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short?>("Loaitaikhoan")
                        .HasColumnType("smallint");

                    b.Property<short?>("Lock")
                        .HasColumnType("smallint");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int?>("Solop")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<string>("Validatecode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ViewAccount");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.ViewChucDanh", b =>
                {
                    b.Property<long>("IdRow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("Cocauid")
                        .HasColumnType("bigint");

                    b.Property<short?>("Disable")
                        .HasColumnType("smallint");

                    b.Property<string>("Ghichu")
                        .HasColumnType("text");

                    b.Property<long?>("IdBp")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdCapquanly")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdCv")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdParent")
                        .HasColumnType("bigint");

                    b.Property<short?>("Isleading")
                        .HasColumnType("smallint");

                    b.Property<short?>("Isstop")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Macd")
                        .HasColumnType("text");

                    b.Property<string>("Motacongviec")
                        .HasColumnType("text");

                    b.Property<long?>("Nguoisua")
                        .HasColumnType("bigint");

                    b.Property<long?>("Nhom")
                        .HasColumnType("bigint");

                    b.Property<int?>("Sonhanviencan")
                        .HasColumnType("integer");

                    b.Property<string>("Tenchucdanh")
                        .HasColumnType("text");

                    b.Property<string>("Tentienganh")
                        .HasColumnType("text");

                    b.Property<short?>("Visiblebophan")
                        .HasColumnType("smallint");

                    b.Property<short?>("Visiblecap")
                        .HasColumnType("smallint");

                    b.Property<int?>("Vitri")
                        .HasColumnType("integer");

                    b.Property<string>("Yeucaubangcap")
                        .HasColumnType("text");

                    b.Property<string>("Yeucaukynangkhac")
                        .HasColumnType("text");

                    b.Property<string>("Yeucaukynanglamviec")
                        .HasColumnType("text");

                    b.HasKey("IdRow");

                    b.ToTable("ViewChucDanh");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.ViewCoCauToChuc", b =>
                {
                    b.Property<long>("Rowid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("Capcocau")
                        .HasColumnType("integer");

                    b.Property<int?>("Chedolamviec")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<long?>("Createdby")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Createddate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("Custemerid")
                        .HasColumnType("bigint");

                    b.Property<long?>("Deletedby")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleteddate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short?>("Disable")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Loaidonvi")
                        .HasColumnType("integer");

                    b.Property<long?>("Modifiedby")
                        .HasColumnType("bigint");

                    b.Property<long?>("Parentid")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("Vitri")
                        .HasColumnType("integer");

                    b.HasKey("Rowid");

                    b.ToTable("ViewCoCauToChuc");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.ViewNhanVien", b =>
                {
                    b.Property<long>("IdNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<short?>("Alloweditchucdanh")
                        .HasColumnType("smallint");

                    b.Property<short?>("Alloweditsalary")
                        .HasColumnType("smallint");

                    b.Property<long?>("Bangcap")
                        .HasColumnType("bigint");

                    b.Property<string>("Bangcapkhac")
                        .HasColumnType("text");

                    b.Property<int?>("Batdautungay")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Bcbhxht")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short?>("Bhtn")
                        .HasColumnType("smallint");

                    b.Property<string>("Boithuongthoiviec")
                        .HasColumnType("text");

                    b.Property<int?>("Cachchamcong")
                        .HasColumnType("integer");

                    b.Property<int?>("Cachtinhluong")
                        .HasColumnType("integer");

                    b.Property<int?>("Cachtinhthuetncn")
                        .HasColumnType("integer");

                    b.Property<long?>("Calamviec")
                        .HasColumnType("bigint");

                    b.Property<string>("Cancuthoiviec")
                        .HasColumnType("text");

                    b.Property<double?>("Cannang")
                        .HasColumnType("double precision");

                    b.Property<short?>("Cd")
                        .HasColumnType("smallint");

                    b.Property<int?>("Chieucao")
                        .HasColumnType("integer");

                    b.Property<string>("Chinhanhnganhang")
                        .HasColumnType("text");

                    b.Property<int?>("Chucdanh")
                        .HasColumnType("integer");

                    b.Property<long?>("Chucvu")
                        .HasColumnType("bigint");

                    b.Property<string>("Chucvucongdoan")
                        .HasColumnType("text");

                    b.Property<string>("Chucvutrongdang")
                        .HasColumnType("text");

                    b.Property<string>("Chucvutrongdoan")
                        .HasColumnType("text");

                    b.Property<string>("Chutaikhoan")
                        .HasColumnType("text");

                    b.Property<string>("Chuyenmon")
                        .HasColumnType("text");

                    b.Property<string>("Chuyennganh")
                        .HasColumnType("text");

                    b.Property<string>("Cmnd")
                        .HasColumnType("text");

                    b.Property<long?>("Cocauid")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Congtrocapvaoluongthang")
                        .HasColumnType("text");

                    b.Property<string>("Congviecnoio1")
                        .HasColumnType("text");

                    b.Property<string>("Congviecnoio2")
                        .HasColumnType("text");

                    b.Property<long?>("Createduser")
                        .HasColumnType("bigint");

                    b.Property<short?>("Danhanviec")
                        .HasColumnType("smallint");

                    b.Property<long?>("Dantoc")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Datecreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Dathongbao")
                        .HasColumnType("integer");

                    b.Property<short?>("Datrasobhxh")
                        .HasColumnType("smallint");

                    b.Property<string>("Defaultmoduleid")
                        .HasColumnType("text");

                    b.Property<string>("DiachiNguoilienhe")
                        .HasColumnType("text");

                    b.Property<long?>("Diadiemlamviec")
                        .HasColumnType("bigint");

                    b.Property<string>("Diemmanh")
                        .HasColumnType("text");

                    b.Property<string>("Diemyeu")
                        .HasColumnType("text");

                    b.Property<short?>("Disable")
                        .HasColumnType("smallint");

                    b.Property<short?>("Dongbhxh")
                        .HasColumnType("smallint");

                    b.Property<short?>("Dongbhyt")
                        .HasColumnType("smallint");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Emailcanhan")
                        .HasColumnType("text");

                    b.Property<int?>("Enrollnumber")
                        .HasColumnType("integer");

                    b.Property<string>("ExtraId")
                        .HasColumnType("text");

                    b.Property<string>("Filecv")
                        .HasColumnType("text");

                    b.Property<string>("Filethoiviec")
                        .HasColumnType("text");

                    b.Property<string>("Ghichu")
                        .HasColumnType("text");

                    b.Property<string>("Ghichubhxh")
                        .HasColumnType("text");

                    b.Property<string>("Ghichuquansu")
                        .HasColumnType("text");

                    b.Property<string>("Ghichuthoiviec")
                        .HasColumnType("text");

                    b.Property<string>("Ghichutrudongphuc")
                        .HasColumnType("text");

                    b.Property<long?>("Giadinhchinhsach")
                        .HasColumnType("bigint");

                    b.Property<int?>("Hangbenhbinh")
                        .HasColumnType("integer");

                    b.Property<long?>("Hangchucdanh")
                        .HasColumnType("bigint");

                    b.Property<int?>("Hangthuongbinh")
                        .HasColumnType("integer");

                    b.Property<double?>("Hesogv")
                        .HasColumnType("double precision");

                    b.Property<int?>("Hinhthucluong")
                        .HasColumnType("integer");

                    b.Property<int?>("Hinhthucthoiviec")
                        .HasColumnType("integer");

                    b.Property<string>("Hoancanhnhao")
                        .HasColumnType("text");

                    b.Property<string>("Hocham")
                        .HasColumnType("text");

                    b.Property<string>("Holot")
                        .HasColumnType("text");

                    b.Property<long?>("IdBangtotnghiep")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdBp")
                        .HasColumnType("bigint");

                    b.Property<string>("IdCa")
                        .HasColumnType("text");

                    b.Property<long?>("IdChedolamviec")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdChedonghi")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdChucdanh")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdChucdanhGv")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdChucdanhluanchuyen")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdCvquanly")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdCvtd")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdDv")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdHd")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdHs")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdKhoa")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdNganhang")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdNganhhoc")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdNvcu")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdQuanly")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdTo")
                        .HasColumnType("bigint");

                    b.Property<short?>("Ischeck")
                        .HasColumnType("smallint");

                    b.Property<short?>("Iscutrutren180ngay")
                        .HasColumnType("smallint");

                    b.Property<short?>("IsdongpcdDn")
                        .HasColumnType("smallint");

                    b.Property<short?>("Isforeigner")
                        .HasColumnType("smallint");

                    b.Property<short?>("Iskhongkhautruttncn")
                        .HasColumnType("smallint");

                    b.Property<short?>("Iskycamketthue")
                        .HasColumnType("smallint");

                    b.Property<int?>("Isluonggross")
                        .HasColumnType("integer");

                    b.Property<short?>("Isprint")
                        .HasColumnType("smallint");

                    b.Property<long?>("Kiemnhiem")
                        .HasColumnType("bigint");

                    b.Property<double?>("Kinhnghiemlvnh")
                        .HasColumnType("double precision");

                    b.Property<string>("Kynangngonngu")
                        .HasColumnType("text");

                    b.Property<int?>("Lanbaogiambhxh")
                        .HasColumnType("integer");

                    b.Property<int?>("Lanbaotangbhxh")
                        .HasColumnType("integer");

                    b.Property<short?>("Languoikhuyettat")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("Lastmodifieduser")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Lastupdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("Loaigiangvien")
                        .HasColumnType("bigint");

                    b.Property<int?>("Loaihopdong")
                        .HasColumnType("integer");

                    b.Property<long?>("Loainhanvien")
                        .HasColumnType("bigint");

                    b.Property<int?>("Loaithoiviec")
                        .HasColumnType("integer");

                    b.Property<string>("Luongcb")
                        .HasColumnType("text");

                    b.Property<string>("Luongchenhlech")
                        .HasColumnType("text");

                    b.Property<string>("Luongcoban")
                        .HasColumnType("text");

                    b.Property<string>("Luongkd")
                        .HasColumnType("text");

                    b.Property<string>("Luongthuviec")
                        .HasColumnType("text");

                    b.Property<string>("Luongvtcv")
                        .HasColumnType("text");

                    b.Property<string>("Lydothoiviec")
                        .HasColumnType("text");

                    b.Property<string>("Mabenhvien")
                        .HasColumnType("text");

                    b.Property<string>("Macd")
                        .HasColumnType("text");

                    b.Property<string>("Manv")
                        .HasColumnType("text");

                    b.Property<string>("Masothue")
                        .HasColumnType("text");

                    b.Property<string>("Mataikhoan")
                        .HasColumnType("text");

                    b.Property<int?>("Mauinid")
                        .HasColumnType("integer");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<string>("Mongiangday")
                        .HasColumnType("text");

                    b.Property<string>("Namsinh")
                        .HasColumnType("text");

                    b.Property<string>("Namsinhchuho")
                        .HasColumnType("text");

                    b.Property<int?>("Namthamgiabh")
                        .HasColumnType("integer");

                    b.Property<int?>("Namtotnghiep")
                        .HasColumnType("integer");

                    b.Property<string>("NanocoCackhoanbosungkhac")
                        .HasColumnType("text");

                    b.Property<short?>("NanocoIsphobiennoiquy")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("Ngaybaogiambhxh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaybatdaudaotao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaybatdaudongbhtn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaybatdaudongbhxh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaybatdauthuviec")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaybatdautinhthamnien")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaycap")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaycapbhyt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaycapgplx")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaycapmst")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaycappassport")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaycapsobhxh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ngaycapsolaodong")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Ngaycapthebhyt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaycapthedang")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngayhethanbhxh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngayhethanbhyt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngayhethangplx")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngayhethanpassport")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngayhethanthuviec")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngayketthucdaotao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaykythoiviec")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaynhanviecdukien")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaynhapngu")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaysinhchuho")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgaythamgiaOt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ngaythamgiabhxh")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Ngaythamgiacongdoan")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaythoiviec")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaytrasobhxh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngaytrathe")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngayvaobienche")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngayvaocty")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ngayvaodang")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Ngayvaodangchinthuc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ngayvaodoan")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Ngayvaongachvienchuc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Ngayxuatngu")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nguoigioithieu1")
                        .HasColumnType("text");

                    b.Property<string>("Nguoigioithieu2")
                        .HasColumnType("text");

                    b.Property<string>("Nguoikythoiviec")
                        .HasColumnType("text");

                    b.Property<string>("Nguoilienhe")
                        .HasColumnType("text");

                    b.Property<long?>("Nguontuyendungid")
                        .HasColumnType("bigint");

                    b.Property<int?>("Nhommau")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<string>("Noicap")
                        .HasColumnType("text");

                    b.Property<long?>("Noicapgplx")
                        .HasColumnType("bigint");

                    b.Property<string>("Noicappassport")
                        .HasColumnType("text");

                    b.Property<string>("Noicapthedang")
                        .HasColumnType("text");

                    b.Property<long?>("Noidangkykcb")
                        .HasColumnType("bigint");

                    b.Property<string>("Noidungcancu")
                        .HasColumnType("text");

                    b.Property<string>("Noidungnoinhan")
                        .HasColumnType("text");

                    b.Property<string>("Noinamtotnghiep")
                        .HasColumnType("text");

                    b.Property<string>("Noisinh")
                        .HasColumnType("text");

                    b.Property<string>("Noivaodang")
                        .HasColumnType("text");

                    b.Property<string>("Noivaodangchinhthuc")
                        .HasColumnType("text");

                    b.Property<string>("Passport")
                        .HasColumnType("text");

                    b.Property<string>("Phai")
                        .HasColumnType("text");

                    b.Property<long?>("Projectid")
                        .HasColumnType("bigint");

                    b.Property<long?>("Quanham")
                        .HasColumnType("bigint");

                    b.Property<string>("QuanheNguoilienhe")
                        .HasColumnType("text");

                    b.Property<string>("Quanhegiadinh")
                        .HasColumnType("text");

                    b.Property<string>("Quanhevoichuho")
                        .HasColumnType("text");

                    b.Property<string>("Quatrinhcongtac")
                        .HasColumnType("text");

                    b.Property<string>("Quatrinhhoctap")
                        .HasColumnType("text");

                    b.Property<string>("Quoctich")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReNgaythamgiaOt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SodienthoaiNguoilienhe")
                        .HasColumnType("text");

                    b.Property<double?>("Sogiolamviec")
                        .HasColumnType("double precision");

                    b.Property<string>("Sogplx")
                        .HasColumnType("text");

                    b.Property<int?>("Songayphep")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Songayphepconlai")
                        .HasColumnType("numeric");

                    b.Property<int?>("Songuoiphuthuoc")
                        .HasColumnType("integer");

                    b.Property<string>("Soqdthoiviec")
                        .HasColumnType("text");

                    b.Property<string>("Sosobhxh")
                        .HasColumnType("text");

                    b.Property<string>("Sosobhyt")
                        .HasColumnType("text");

                    b.Property<string>("Sosohokhau")
                        .HasColumnType("text");

                    b.Property<string>("Sosolaodong")
                        .HasColumnType("text");

                    b.Property<string>("Sotaikhoan")
                        .HasColumnType("text");

                    b.Property<string>("Sotaikhoan1")
                        .HasColumnType("text");

                    b.Property<string>("Sothe")
                        .HasColumnType("text");

                    b.Property<string>("Sothebhyt")
                        .HasColumnType("text");

                    b.Property<string>("Sothedang")
                        .HasColumnType("text");

                    b.Property<int?>("Staffgroupid")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<short?>("Tamnghi")
                        .HasColumnType("smallint");

                    b.Property<string>("TamtruDiachi")
                        .HasColumnType("text");

                    b.Property<long?>("TamtruHuyen")
                        .HasColumnType("bigint");

                    b.Property<string>("TamtruPhone")
                        .HasColumnType("text");

                    b.Property<long?>("TamtruTinh")
                        .HasColumnType("bigint");

                    b.Property<long?>("TamtruXa")
                        .HasColumnType("bigint");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.Property<string>("Tenbv")
                        .HasColumnType("text");

                    b.Property<string>("Tenchucdanh")
                        .HasColumnType("text");

                    b.Property<string>("Tenchucvu")
                        .HasColumnType("text");

                    b.Property<string>("Tenchuho")
                        .HasColumnType("text");

                    b.Property<string>("Tennguyenquan")
                        .HasColumnType("text");

                    b.Property<string>("Tentruongtotnghiep")
                        .HasColumnType("text");

                    b.Property<int?>("Thangthamgiabh")
                        .HasColumnType("integer");

                    b.Property<short?>("Thanhtoanquanh")
                        .HasColumnType("smallint");

                    b.Property<short?>("Thoiviec")
                        .HasColumnType("smallint");

                    b.Property<string>("ThoiviecLydoEn")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ThoiviecNgaythoiviectheodon")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ThoiviecNgayvietdon")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ThuongtruDiachi")
                        .HasColumnType("text");

                    b.Property<long?>("ThuongtruHuyen")
                        .HasColumnType("bigint");

                    b.Property<string>("ThuongtruPhone")
                        .HasColumnType("text");

                    b.Property<long?>("ThuongtruTinh")
                        .HasColumnType("bigint");

                    b.Property<long?>("ThuongtruXa")
                        .HasColumnType("bigint");

                    b.Property<long?>("Tinh")
                        .HasColumnType("bigint");

                    b.Property<short?>("Tinhluongrieng")
                        .HasColumnType("smallint");

                    b.Property<long?>("Tinhtrang")
                        .HasColumnType("bigint");

                    b.Property<long?>("Tinhtranghn")
                        .HasColumnType("bigint");

                    b.Property<string>("Tinhtranghonnhan")
                        .HasColumnType("text");

                    b.Property<string>("Tinhtrangsuckhoe")
                        .HasColumnType("text");

                    b.Property<string>("Toadodiachitamtru")
                        .HasColumnType("text");

                    b.Property<string>("Toadodiachithuongtru")
                        .HasColumnType("text");

                    b.Property<long?>("Tongiao")
                        .HasColumnType("bigint");

                    b.Property<string>("Tongthunhap")
                        .HasColumnType("text");

                    b.Property<string>("Totnghiepnganh")
                        .HasColumnType("text");

                    b.Property<short?>("Trathe")
                        .HasColumnType("smallint");

                    b.Property<string>("Trinhdo")
                        .HasColumnType("text");

                    b.Property<long?>("Trinhdochinhtri")
                        .HasColumnType("bigint");

                    b.Property<long?>("Trinhdoquanlynhanuoc")
                        .HasColumnType("bigint");

                    b.Property<long?>("Trinhdovitinh")
                        .HasColumnType("bigint");

                    b.Property<string>("Trocapkhac")
                        .HasColumnType("text");

                    b.Property<string>("Trocapthoiviec")
                        .HasColumnType("text");

                    b.Property<long?>("Truongtotnghiep")
                        .HasColumnType("bigint");

                    b.Property<string>("Truvaoluongthang")
                        .HasColumnType("text");

                    b.HasKey("IdNv");

                    b.ToTable("ViewNhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
