// <auto-generated />
using System;
using APICore_SoanDeThi.Models.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace APICore_SoanDeThi.Migrations
{
    [DbContext(typeof(SoanDeThi_DbContext))]
    [Migration("20220107094512_updateRequireBaiHoc")]
    partial class updateRequireBaiHoc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.BaiHoc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("HocKy")
                        .HasColumnType("integer");

                    b.Property<long>("IdChuong")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MaBaiHoc")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("NguoiSua")
                        .HasColumnType("bigint");

                    b.Property<long>("NguoiTao")
                        .HasColumnType("bigint");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("integer");

                    b.Property<string>("TenBaiHoc")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BaiHoc");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.BaiKiemTra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("IdGroup")
                        .HasColumnType("bigint");

                    b.Property<string>("MaDe")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BaiKiemTra");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.BaiKiemTra_ChiTiet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("IdBaiKiemTra")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCauHoi")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BaiKiemTra_ChiTiet");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.BaiKiemTra_Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CauBiet")
                        .HasColumnType("integer");

                    b.Property<int>("CauHieu")
                        .HasColumnType("integer");

                    b.Property<int>("CauVanDungCao")
                        .HasColumnType("integer");

                    b.Property<int>("CauVanDungThap")
                        .HasColumnType("integer");

                    b.Property<int>("HocKy")
                        .HasColumnType("integer");

                    b.Property<long>("IdMonHoc")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<byte>("Lop")
                        .HasColumnType("smallint");

                    b.Property<string>("NamHoc")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("NguoiSua")
                        .HasColumnType("bigint");

                    b.Property<long>("NguoiTao")
                        .HasColumnType("bigint");

                    b.Property<int>("SoLuongDe")
                        .HasColumnType("integer");

                    b.Property<string>("TenBaiKiemTra")
                        .HasColumnType("text");

                    b.Property<int>("ThoiGianLamBai")
                        .HasColumnType("integer");

                    b.Property<short>("TrangThai")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("BaiKiemTra_Group");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.ChuongMonHoc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("IdMonHoc")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<byte>("Lop")
                        .HasColumnType("smallint");

                    b.Property<string>("MaChuong")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("NguoiSua")
                        .HasColumnType("bigint");

                    b.Property<long>("NguoiTao")
                        .HasColumnType("bigint");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("integer");

                    b.Property<string>("TenChuong")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChuongMonHoc");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.Lop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<long>("IdChuNhiem")
                        .HasColumnType("bigint");

                    b.Property<long>("IdNienKhoa")
                        .HasColumnType("bigint");

                    b.Property<string>("Loai")
                        .HasColumnType("text");

                    b.Property<string>("NgaySua")
                        .HasColumnType("text");

                    b.Property<string>("NgayTao")
                        .HasColumnType("text");

                    b.Property<long?>("NguoiSua")
                        .HasColumnType("bigint");

                    b.Property<long>("NguoiTao")
                        .HasColumnType("bigint");

                    b.Property<string>("TenLop")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lop");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.MonHoc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MaMonHoc")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("NguoiSua")
                        .HasColumnType("bigint");

                    b.Property<long>("NguoiTao")
                        .HasColumnType("bigint");

                    b.Property<string>("TenMonHoc")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.NienKhoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<string>("NgaySua")
                        .HasColumnType("text");

                    b.Property<string>("NgayTao")
                        .HasColumnType("text");

                    b.Property<long?>("NguoiSua")
                        .HasColumnType("bigint");

                    b.Property<long>("NguoiTao")
                        .HasColumnType("bigint");

                    b.Property<string>("TenNienKhoa")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NienKhoa");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.PqAccountPermit", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UserName", "Code");

                    b.ToTable("PQ_Account_Permit");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.PqGroup", b =>
                {
                    b.Property<long>("IdGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdGroup");

                    b.ToTable("PQ_Group");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.PqGroupAccount", b =>
                {
                    b.Property<long>("IdGroup")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdGroup", "UserName");

                    b.ToTable("PQ_Group_Account");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.PqGroupPermit", b =>
                {
                    b.Property<long>("IdGroup")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdGroup", "Code");

                    b.ToTable("PQ_Group_Permit");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.PqPermission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CodeGroup")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("IdGroup")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDisable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short?>("Position")
                        .HasColumnType("smallint");

                    b.HasKey("Code");

                    b.ToTable("PQ_Permission");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.PqPermissionGroup", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IdParent")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short?>("Position")
                        .HasColumnType("smallint");

                    b.HasKey("Code");

                    b.ToTable("PQ_Permission_Group");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.SysConfigDashboard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Component")
                        .HasColumnType("text");

                    b.Property<bool>("Default")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("RouterLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SysConfigDashboard");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.DatabaseContext.SysRequestLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("MaDinhDanh")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayXacNhan")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("NguoiXacNhan")
                        .HasColumnType("bigint");

                    b.Property<string>("ThongTinThietBi")
                        .HasColumnType("text");

                    b.Property<short?>("TinhTrang")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("SysRequestLogin");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.PqMainMenu", b =>
                {
                    b.Property<long>("IdMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AllowCode")
                        .HasColumnType("text");

                    b.Property<long?>("AllowPermit")
                        .HasColumnType("bigint");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<long?>("IdModule")
                        .HasColumnType("bigint");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<short?>("Position")
                        .HasColumnType("smallint");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("IdMain");

                    b.ToTable("PQ_MainMenu");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.PqModule", b =>
                {
                    b.Property<long>("IdModule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AllowCode")
                        .HasColumnType("text");

                    b.Property<long?>("AllowPermit")
                        .HasColumnType("bigint");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<short?>("Position")
                        .HasColumnType("smallint");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("IdModule");

                    b.ToTable("PQ_Module");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.PqSubMenu", b =>
                {
                    b.Property<long>("IdSubMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AllowCode")
                        .HasColumnType("text");

                    b.Property<long?>("AllowPermit")
                        .HasColumnType("bigint");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<long?>("IdMainMenu")
                        .HasColumnType("bigint");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("PageKey")
                        .HasColumnType("text");

                    b.Property<short?>("Position")
                        .HasColumnType("smallint");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("IdSubMenu");

                    b.ToTable("PQ_SubMenu");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte>("CorrectOption")
                        .HasColumnType("smallint");

                    b.Property<long>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("IdBaiHoc")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdBaiKiemTra_Group")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<byte>("Level")
                        .HasColumnType("smallint");

                    b.Property<long?>("ModifyBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OptionA")
                        .HasColumnType("text");

                    b.Property<string>("OptionB")
                        .HasColumnType("text");

                    b.Property<string>("OptionC")
                        .HasColumnType("text");

                    b.Property<string>("OptionD")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.SysAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("NguoiTao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SysAttachment");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.SysAttachmentDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("AttachmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<bool>("IsDisable")
                        .HasColumnType("boolean");

                    b.Property<string>("LoaiFile")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("NguoiSua")
                        .HasColumnType("bigint");

                    b.Property<long>("NguoiTao")
                        .HasColumnType("bigint");

                    b.Property<string>("TenFile")
                        .HasColumnType("text");

                    b.Property<string>("TenFileGoc")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SysAttachmentDetail");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.ViewAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("Authentype")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Createddate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DPassword")
                        .HasColumnType("text");

                    b.Property<int?>("Defaultmodule")
                        .HasColumnType("integer");

                    b.Property<short?>("Disable")
                        .HasColumnType("smallint");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Expirevalidate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Exppassword")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Faillogin")
                        .HasColumnType("integer");

                    b.Property<long?>("IdNv")
                        .HasColumnType("bigint");

                    b.Property<short?>("Isadmin")
                        .HasColumnType("smallint");

                    b.Property<short?>("Iscreateldapaccount")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Lastlogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Lastpasschg")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Lastsend")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short?>("Loaitaikhoan")
                        .HasColumnType("smallint");

                    b.Property<short?>("Lock")
                        .HasColumnType("smallint");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<int?>("Solop")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<string>("Validatecode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ViewAccount");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.ViewChucDanh", b =>
                {
                    b.Property<long>("IdRow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("Cocauid")
                        .HasColumnType("bigint");

                    b.Property<short?>("Disable")
                        .HasColumnType("smallint");

                    b.Property<string>("Ghichu")
                        .HasColumnType("text");

                    b.Property<long?>("IdBp")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdCapquanly")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdCv")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdParent")
                        .HasColumnType("bigint");

                    b.Property<short?>("Isleading")
                        .HasColumnType("smallint");

                    b.Property<short?>("Isstop")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Macd")
                        .HasColumnType("text");

                    b.Property<string>("Motacongviec")
                        .HasColumnType("text");

                    b.Property<long?>("Nguoisua")
                        .HasColumnType("bigint");

                    b.Property<long?>("Nhom")
                        .HasColumnType("bigint");

                    b.Property<int?>("Sonhanviencan")
                        .HasColumnType("integer");

                    b.Property<string>("Tenchucdanh")
                        .HasColumnType("text");

                    b.Property<string>("Tentienganh")
                        .HasColumnType("text");

                    b.Property<short?>("Visiblebophan")
                        .HasColumnType("smallint");

                    b.Property<short?>("Visiblecap")
                        .HasColumnType("smallint");

                    b.Property<int?>("Vitri")
                        .HasColumnType("integer");

                    b.Property<string>("Yeucaubangcap")
                        .HasColumnType("text");

                    b.Property<string>("Yeucaukynangkhac")
                        .HasColumnType("text");

                    b.Property<string>("Yeucaukynanglamviec")
                        .HasColumnType("text");

                    b.HasKey("IdRow");

                    b.ToTable("ViewChucDanh");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.ViewCoCauToChuc", b =>
                {
                    b.Property<long>("Rowid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("Capcocau")
                        .HasColumnType("integer");

                    b.Property<int?>("Chedolamviec")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<long?>("Createdby")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Createddate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("Custemerid")
                        .HasColumnType("bigint");

                    b.Property<long?>("Deletedby")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Deleteddate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short?>("Disable")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Loaidonvi")
                        .HasColumnType("integer");

                    b.Property<long?>("Modifiedby")
                        .HasColumnType("bigint");

                    b.Property<long?>("Parentid")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("Vitri")
                        .HasColumnType("integer");

                    b.HasKey("Rowid");

                    b.ToTable("ViewCoCauToChuc");
                });

            modelBuilder.Entity("APICore_SoanDeThi.Models.ViewNhanVien", b =>
                {
                    b.Property<long>("IdNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AllowCode")
                        .HasColumnType("integer");

                    b.Property<long?>("Cocauid")
                        .HasColumnType("bigint");

                    b.Property<short?>("Disable")
                        .HasColumnType("smallint");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Holot")
                        .HasColumnType("text");

                    b.Property<long?>("IdChucdanh")
                        .HasColumnType("bigint");

                    b.Property<string>("IdLop")
                        .HasColumnType("text");

                    b.Property<long?>("IdMonHoc")
                        .HasColumnType("bigint");

                    b.Property<string>("Manv")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Phai")
                        .HasColumnType("text");

                    b.Property<string>("SodienthoaiNguoilienhe")
                        .HasColumnType("text");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.Property<bool?>("isStudent")
                        .HasColumnType("boolean");

                    b.HasKey("IdNv");

                    b.ToTable("ViewNhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
